Fix English
qbcore-framework/qb-garbagejob pull request #11
Opened 2021-09-23 07:04 UTC by Seaqn

fixed the notifications to be more understandable

2021-09-23 07:06 UTC, darknight2590 commented
and truckerjob

2021-10-14 11:11 UTC, papabendi requested changes
Although, the original costs are $1000, could be better to have it referring to a variable for the cost. That way it could be changed.

2021-10-14 11:11 UTC, papabendi commented on client/main.lua
> +                                        QBCore.Functions.Notify("$250 dollar deposit was returned!")
QBCore.Functions.Notify("Your $250 deposit has been returned!")

2021-10-14 11:11 UTC, papabendi commented on client/main.lua
> +                                            QBCore.Functions.Notify("$250 dollar deposit was taken out of your bank account!")
QBCore.Functions.Notify("The $250 deposit has been taken out of your bank account!")

2021-10-14 11:11 UTC, papabendi commented on client/main.lua
> +                                            QBCore.Functions.Notify("You have started work, first location marked on GPS!")
QBCore.Functions.Notify("You have started work. Your first location has been marked on the GPS!")

2021-10-14 11:11 UTC, papabendi commented on client/main.lua
> +                                        QBCore.Functions.Notify("You dont have enough money to pay the deposit.. Deposit cost is $250 dollars")
QBCore.Functions.Notify("You dont have enough money to pay the deposit.. The deposit cost is $250")

2021-11-01 02:37 UTC, closed without merging